apiVersion: apps/v1
kind: Deployment #k8s resources kind we are creating
metadata:
  name: spring-boot-k8s-deployment
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 2 #No of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-boot-k8s
          image: hemantdhage/devops-integration # Image that will be used to create containers in cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 #Port that container will run on cluster

---

apiVersion: v1 # K8s API version
kind: Service #k8s resources kind we are creating
metadata: # Metadata of resource kind which we are creating
  name: springboot-k8ssvc
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: "TCP"
      port: 8080 # Port where service will be running in cluster
      targetPort: 8080 # Port exposed by service
  type: NodePort # Type of service